services:
  # Backend service
  - type: web
    name: full-stack-note-taking-application
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend service
  - type: web
    name: note-taking-frontend
    env: static
    plan: free
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Listing root directory:"
      ls -la
      echo "Listing client directory:"
      ls -la client/
      echo "Listing client/public directory:"
      ls -la client/public/
      cd client
      npm install
      npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
